<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>hotelRatingAndInvoiceDownload</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ee6a7d16-6f67-4b4e-a390-2dd74a379bad</testSuiteGuid>
   <testCaseLink>
      <guid>f3b0c2e6-52fe-4fc5-b9e3-3afee1f6987d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Assignment/02_Scenario 2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30c1a9c8-36b3-4eca-9135-31ef3c136358</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fff1eccf-d572-4779-b894-9d2fde7c9fe5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b38d43c-9e34-49b8-aace-b582e7851779</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
