<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Invoice</name>
   <tag></tag>
   <elementGuidId>839a8839-c3b8-4e28-ad90-8307674e2f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='bookings']/div[2]/div/a[text()='Invoice']</value>
   </webElementProperties>
</WebElementEntity>
